<a href="https://colab.research.google.com/github/bohara10/ML_training/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

what we will cover?

1.Creating arrays
2.Multidimensional array
3.Randomly generated arrays
4.Element wise operations
5.Summarrizing operations

# single dimensional arrays

In [29]:
#creating an array with all elements 1
import numpy as np
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
#creating an array of size 10 with all elements 3

np.full(10, 3)

In [ ]:
#create an array with all the emlements to be zeros
np.zeros(5)

In [ ]:
#create an array with
np.array([1, 2, 3, 4, 5])

In [ ]:
np.arange(3,10)

In [ ]:
#create an array with evenly  spaced numbers within a specified range
np.linspace(0,100,11)

# multi dimensional arrays


2.Multidimensional array

In [7]:
np.zeros((3,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

a[0,1] = 20
a
a[3,]


array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [22]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

3.Randomly generated arrays

### Randomly generated arrays

- NumPy can create arrays filled with random numbers
- To ensures the reproductbility ,you can seta seed using np.random.seed().it will generate the exact same random numbers for each executions
-if you remove or change the seed values , the sequence of random numbers will be changed

In [25]:
np.random.rand(5)

array([0.76378997, 0.18089147, 0.66199537, 0.52486665, 0.20265626])

In [28]:
np.random.seed(5)
np.random.rand(5)

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119])

In [31]:
np.random.randn(5,2)

array([[ 1.36758552,  0.57470769],
       [-1.88576241,  0.17092537],
       [-0.40309331,  1.63762849],
       [-0.60529785, -1.59441507],
       [ 0.91187364, -1.44384155]])

In [33]:
np.random.randint(low=0, high=100 ,size=(5,2))

array([[41, 62],
       [ 1, 82],
       [16, 78],
       [ 5, 58],
       [ 0, 80]])

4.Element wise operations

5.Summarrizing operations