<a href="https://colab.research.google.com/github/bohara10/ML_training/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

what we will cover?

1.Creating arrays
2.Multidimensional array
3.Randomly generated arrays
4.Element wise operations
5.Summarrizing operations

# single dimensional arrays

In [ ]:
#creating an array with all elements 1
import numpy as np
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
#creating an array of size 10 with all elements 3

np.full(10, 3)

In [ ]:
#create an array with all the emlements to be zeros
np.zeros(5)

In [ ]:
#create an array with
np.array([1, 2, 3, 4, 5])

In [ ]:
np.arange(3,10)

In [ ]:
#create an array with evenly  spaced numbers within a specified range
np.linspace(0,100,11)

# multi dimensional arrays


2.Multidimensional array

In [ ]:
np.zeros((3,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

a[0,1] = 20
a
a[3,]


array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [ ]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

3.Randomly generated arrays

### Randomly generated arrays

- NumPy can create arrays filled with random numbers
- To ensures the reproductbility ,you can seta seed using np.random.seed().it will generate the exact same random numbers for each executions
-if you remove or change the seed values , the sequence of random numbers will be changed

In [5]:
import numpy as np
np.random.rand(5)

array([0.74024225, 0.23482652, 0.6449435 , 0.41588294, 0.59719366])

In [6]:
np.random.seed(5)
np.random.rand(5)

array([0.22199317, 0.87073231, 0.20671916, 0.91861091, 0.48841119])

In [8]:
np.random.randn(5,2)

array([[-1.19276461, -0.20487651],
       [-0.35882895,  0.6034716 ],
       [-1.66478853, -0.70017904],
       [ 1.15139101,  1.85733101],
       [-1.51117956,  0.64484751]])

In [7]:
np.random.randint(low=0, high=100 ,size=(5,2))

array([[62, 27],
       [30, 80],
       [ 7, 76],
       [15, 53],
       [80, 27]])

4.Element wise operations

In [11]:
import numpy as np
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [12]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [14]:
#comparison operations
a


array([0, 1, 2, 3, 4])

In [15]:
a>=b

array([False, False, False, False, False])

In [16]:
a>=2

array([False, False,  True,  True,  True])

In [17]:
a > 2

array([False, False, False,  True,  True])

In [18]:
#summarizing of the data
#Numpy provides functions for summarizing array data

a


array([0, 1, 2, 3, 4])

In [19]:
a.std()

1.4142135623730951

In [22]:
a.min()


0

In [21]:
a.max()

4

5.Summarrizing operations